version: "3.9"
services:
  grpcurlshorner:
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    depends_on:
      - database
    networks:
      - default
    env_file:
      - .env
    ports:
      - "8083:8083"
    container_name: urlshortner
  database:
    image: postgres
    restart: always
    env_file:
      - .env
    ports:
      - "54321:5432"

